//src/app/layout.js

import { getFsVisitorData } from '@/helpers/flagship'
import './globals.css'
import { FlagshipProvider } from '@flagship.io/react-sdk'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const visitorData = {
    id: "visitorId",
    context: {
      key: "value"
    }
  }

  // Get visitor instance
  const visitor = await getFsVisitorData(visitorData)

  return (
    <html lang="en">
      <body >
        <FlagshipProvider
          envId={process.env.NEXT_PUBLIC_ENV_ID}
          apiKey={process.env.NEXT_PUBLIC_API_KEY}
          initialFlagsData={visitor.getFlagsDataArray()} // set Initial flags data from visitor instance
          visitorData={visitorData} // visitor data
        >
          <div className={"container"}>
            <div className='nav'>
              <Link href="/">Home</Link>
              <Link href="/client-component">client-component page</Link>
              <Link href="/server-component">server-component page</Link>
            </div>
            <main className={"main"}>

              {children}
            </main>
          </div>
        </FlagshipProvider>
      </body>
    </html >
  )
}
