import './globals.css'
import { FlagshipProvider } from '@/components/flagship'
import { getFsVisitorData } from '@/helpers/flagship';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const visitorData = {
    id: "visitorId",
    context: {}
  }

  const visitor = await getFsVisitorData(visitorData)
  return (
    <html lang="en">
      <body >
        <FlagshipProvider
          envId={process.env.NEXT_PUBLIC_ENV_ID}
          apiKey={process.env.NEXT_PUBLIC_API_KEY}
          initialFlagsData={visitor.getFlagsDataArray()}
          visitorData={visitorData}
        >
          {children}
        </FlagshipProvider>
      </body>
    </html>
  )
}
